server:
  port: 9191
  servlet:
    context-path: /v1
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        naming:
          physical-strategy=org: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

# JWT 配置
jwt:
  tokenPrefix: Bearer
  # 存放Token的Header Key
  header: Authorization
  # 密匙key
  secret: laurusJwt
  # 过期时间   单位秒 7天后过期  604800
  expiration: 3600
  # 自定义token 前缀字符
  tokenHead: Bearer-
  # 超时时间   单位秒
  access_token: 3600
  # 刷新token时间   单位秒
  refresh_token: 3600
  route:
    authentication:
      path: /login
      refresh: oauth/refresh
      register: login/account


# 配置不需要认证的接口
com:
  example:
    oauth:
      security:
        antMatchers:
          /v1/login/**,
          /v1/version
